package com.example.passkey.controller;

import java.math.BigInteger;
import java.security.AlgorithmParameters;
import java.security.KeyFactory;
import java.security.PublicKey;
import java.security.Signature;
import java.security.spec.ECGenParameterSpec;
import java.security.spec.ECParameterSpec;
import java.security.spec.ECPoint;
import java.security.spec.ECPublicKeySpec;
import java.util.Base64;
import org.bouncycastle.jce.ECNamedCurveTable;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class FidoVerifier {

  private static final Logger logger = LoggerFactory.getLogger(FidoVerifier.class);
  /**
   * Verifies an ECDSA signature generated by an iOS Secure Enclave.
   * * @param publicKeyBase64 The base64 string from SecKeyCopyExternalRepresentation
   * @param challenge The original string sent to the app
   * @param signatureBase64 The base64 signature from SecKeyCreateSignature
   */
  public static boolean verify(String publicKeyBase64, String challenge, String signatureBase64) throws Exception {
    logger.info("Verifying Fido Public Key: {}", publicKeyBase64);
    byte[] publicBytes = Base64.getDecoder().decode(publicKeyBase64);
    byte[] signatureBytes = Base64.getDecoder().decode(signatureBase64);
    byte[] challengeBytes = challenge.getBytes("UTF-8");

// 1. Convert iOS Raw Bytes (X9.62) to Java Public Key
// P-256 raw format is 65 bytes: [0x04][32 bytes X][32 bytes Y]
    KeyFactory kf = KeyFactory.getInstance("EC");
    org.bouncycastle.jce.spec.ECParameterSpec ecSpec = ECNamedCurveTable.getParameterSpec("secp256r1"); // P-256

// Manual coordinate extraction (simplified for PoC)
    byte[] xBytes = new byte[32];
    byte[] yBytes = new byte[32];
    System.arraycopy(publicBytes, 1, xBytes, 0, 32);
    System.arraycopy(publicBytes, 33, yBytes, 0, 32);

    ECPoint point = new ECPoint(new BigInteger(1, xBytes), new BigInteger(1, yBytes));
    ECPublicKeySpec pubSpec = new ECPublicKeySpec(point, getP256ParameterSpec());
    PublicKey publicKey = kf.generatePublic(pubSpec);

// 2. Verify the Signature
    Signature ecdsaVerify = Signature.getInstance("SHA256withECDSA");
    ecdsaVerify.initVerify(publicKey);
    ecdsaVerify.update(challengeBytes);

    return ecdsaVerify.verify(signatureBytes);
  }

  private static ECParameterSpec getP256ParameterSpec() throws Exception {
    AlgorithmParameters params = AlgorithmParameters.getInstance("EC");
    params.init(new ECGenParameterSpec("secp256r1"));
    return params.getParameterSpec(ECParameterSpec.class);
  }
}
